### ISSUE TITLE
Normalize data

### ISSUE THREAD

**Issue by Quichei** [Kinsa/sampen#1]
I think your function must replace  `data[i] += data[i] - mean`with `data[i] = data[i] - mean`

**Comment by bergantine** [comment]
Tell me why? I haven't written a specific unit test for that function, which should, according to the physionet docblock at http://www.physionet.org/physiotools/sampen/c/sampen.c "subtract the mean from data, then divide the data by their standard deviation" but I can assert that the output from the combination does match the output from the physionet samples.

**Comment by Quichei** [comment]
after normalize data variance should be 1 and mean should be 0 .your function doesnt do that ! you are over doing it! in the link you mentioned its `data[i] = data[i] -mean`. you should use that or `data[i] -= mean` . u used Both!

**Comment by bergantine** [comment]
Okay, you could be right. I was shorthanding some `C` code in the transformation to Python. Can you make the mod and write a test case that verifys against the original on Physionet?

**Comment by Quichei** [comment]
```
import numpy as np 
import math
data = [2,3,4]



def foo(data):
    mean = np.mean(data)
    n = len(data)
    var = 0.0
    for i in range(n):
        data[i] = data[i] - mean
        var += data[i] * data[i]

    var = math.sqrt(var / float(n))

    for i in range(n):
        data[i] = data[i] / var
    print(data)
    print(var)
    print(np.mean(data))
    var = 0.0
    mean2 = np.mean(data)
    for i in range(n):
        data[i] = data[i] - mean2
        var += data[i] * data[i]
    var = math.sqrt(var / float(n))
    print(var)

foo(data)
```

I cant do that but this is your function with right statements. I used another loop to calculate var after normalizing.
if you change it back to you statement you can see it doesnt ouput VAR 1 & mean 0 anymore

if you want shorthanded just go with `data[i] -= mean`

!!!! my bad I just saw your code have `+=` instead of `-=`. but same anyway. Variance calculation is that way!

**Comment by bergantine** [comment]
@Decapitary Thanks for the test case. Added that to the test suite and implemented the fix.
